require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe StreamsController do

  # This should return the minimal set of attributes required to create a valid
  # Stream. As you add validations to Stream, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) { { "description" => "MyString" } }

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # StreamsController. Be sure to keep this updated too.
  let(:valid_session) { {} }

  describe "GET index" do
    it "assigns all streams as @streams" do
      stream = Stream.create! valid_attributes
      get :index, {}, valid_session
      assigns(:streams).should eq([stream])
    end
  end

  describe "GET show" do
    it "assigns the requested stream as @stream" do
      stream = Stream.create! valid_attributes
      get :show, {:id => stream.to_param}, valid_session
      assigns(:stream).should eq(stream)
    end
  end

  describe "GET new" do
    it "assigns a new stream as @stream" do
      get :new, {}, valid_session
      assigns(:stream).should be_a_new(Stream)
    end
  end

  describe "GET edit" do
    it "assigns the requested stream as @stream" do
      stream = Stream.create! valid_attributes
      get :edit, {:id => stream.to_param}, valid_session
      assigns(:stream).should eq(stream)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new Stream" do
        expect {
          post :create, {:stream => valid_attributes}, valid_session
        }.to change(Stream, :count).by(1)
      end

      it "assigns a newly created stream as @stream" do
        post :create, {:stream => valid_attributes}, valid_session
        assigns(:stream).should be_a(Stream)
        assigns(:stream).should be_persisted
      end

      it "redirects to the created stream" do
        post :create, {:stream => valid_attributes}, valid_session
        response.should redirect_to(Stream.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved stream as @stream" do
        # Trigger the behavior that occurs when invalid params are submitted
        Stream.any_instance.stub(:save).and_return(false)
        post :create, {:stream => { "description" => "invalid value" }}, valid_session
        assigns(:stream).should be_a_new(Stream)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        Stream.any_instance.stub(:save).and_return(false)
        post :create, {:stream => { "description" => "invalid value" }}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested stream" do
        stream = Stream.create! valid_attributes
        # Assuming there are no other streams in the database, this
        # specifies that the Stream created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        Stream.any_instance.should_receive(:update).with({ "description" => "MyString" })
        put :update, {:id => stream.to_param, :stream => { "description" => "MyString" }}, valid_session
      end

      it "assigns the requested stream as @stream" do
        stream = Stream.create! valid_attributes
        put :update, {:id => stream.to_param, :stream => valid_attributes}, valid_session
        assigns(:stream).should eq(stream)
      end

      it "redirects to the stream" do
        stream = Stream.create! valid_attributes
        put :update, {:id => stream.to_param, :stream => valid_attributes}, valid_session
        response.should redirect_to(stream)
      end
    end

    describe "with invalid params" do
      it "assigns the stream as @stream" do
        stream = Stream.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Stream.any_instance.stub(:save).and_return(false)
        put :update, {:id => stream.to_param, :stream => { "description" => "invalid value" }}, valid_session
        assigns(:stream).should eq(stream)
      end

      it "re-renders the 'edit' template" do
        stream = Stream.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Stream.any_instance.stub(:save).and_return(false)
        put :update, {:id => stream.to_param, :stream => { "description" => "invalid value" }}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested stream" do
      stream = Stream.create! valid_attributes
      expect {
        delete :destroy, {:id => stream.to_param}, valid_session
      }.to change(Stream, :count).by(-1)
    end

    it "redirects to the streams list" do
      stream = Stream.create! valid_attributes
      delete :destroy, {:id => stream.to_param}, valid_session
      response.should redirect_to(streams_url)
    end
  end

end
